# Generated by Django 5.2.8 on 2025-11-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_ph', models.DateTimeField()),
                ('latitude', models.FloatField(default=0.0)),
                ('longtitude', models.FloatField(default=0.0)),
                ('magnitude', models.FloatField(default=0.0)),
                ('location', models.CharField(default='', max_length=500)),
                ('specific_loc', models.CharField(default='', max_length=300)),
                ('general_loc', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
