# Generated by Django 5.2.7 on 2025-11-08 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_earthquakeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('where', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('report_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Rejected', max_length=20)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
